const dummyOrders = [
  {
    id: "ORD-3091",
    date: "April 16, 2025",
    status: "Delivered",
    productType: "Embroidery Digitizing",
    price: "$8",
    progress: 100,
    files: [{ name: "Logo.png", url: "#" }],
    details: "This is a delivered embroidery digitizing order. Files are available for download.",
  },
  {
    id: "ORD-3092",
    date: "April 15, 2025",
    status: "Final Review",
    productType: "Embroidery Digitizing",
    price: "$8",
    progress: 90,
    files: [{ name: "Design_v2.ai", url: "#" }],
    details: "This order is in the final review stage. Please check the design carefully.",
  },
  {
    id: "ORD-3093",
    date: "April 14, 2025",
    status: "Being Digitized",
    productType: "Vector Services",
    price: "$12",
    progress: 50,
    files: [],
    details: "Your vector artwork is currently being digitized. We'll notify you upon completion.",
  },
  {
    id: "ORD-3094",
    date: "April 13, 2025",
    status: "In Queue",
    productType: "Embroidery Patches",
    price: "$10",
    progress: 25,
    files: [],
    details: "This embroidery patch order is in the queue and will begin processing shortly.",
  },
  {
    id: "ORD-3095",
    date: "April 12, 2025",
    status: "Order Placed",
    productType: "Embroidery Digitizing",
    price: "$7",
    progress: 10,
    files: [],
    details: "Your order has been placed successfully. We are reviewing your design.",
  },
];

export { dummyOrders };
